name:                server-post
version:             0.1.0.0
github:              "githubuser/server-post"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/server-post#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- base64-bytestring
# - containers
- configurator
- directory
# - file-embed
- hspec
# - hspec-wai
# - hspec-wai-json
- http-types
- MissingH
- mtl
- postgresql-simple
# - postgresql-simple-migration
- resource-pool
# - scientific
# - scotty
# - sorted-list
# - stm
- text
- time
# - uuid
- wai
- warp
# - wai-extra
library:
  source-dirs: src

executables:
  server-post-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server-post

tests:
  server-post-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server-post
