DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS drafts;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS users;
